version: '3.8'

networks:
  bank_net:

services:
  db:
    build:
      context: .
      target: database
    networks:
      - bank_net
    restart: always
    # volumes:
    #   - .data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
  auth:
    build:
      context: .
      target: authProd
    networks:
      - bank_net
    restart: always
    ports:
      - 4001:3000
