version: '3.8'

networks:
  bank_net:

services:
  db:
    build:
      context: .
      target: database
    networks:
      - bank_net
    restart: always
  auth:
    build:
      context: .
      target: authProd
    networks:
      - bank_net
    restart: always
    ports:
      - 4001:80
