version: '3.8'

networks:
  bank_net:

services:
  postgres:
    image: postgres:alpine
    container_name: postgres-db
    networks:
      - bank_net
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
    volumes:
      - .build/.data/:/var/lib/postgresql/data
    ports:
      - 5432:5432

