networks:
  bank_net:

services:
  db:
    build:
      context: .
      target: database
    networks:
      - bank_net
    restart: always
    ports:
      - 5432:5432
  auth:
    build:
      context: .
      target: authProd
    networks:
      - bank_net
    restart: always
    ports:
      - 4001:80
    environment:
      - DB_URL=postgresql://back:root@db:5432/cardboard_bank
      - AUTH_PORT=80
  api:
    build:
      context: .
      target: apiProd
    networks:
      - bank_net
    restart: always
    ports:
      - 4002:80
    environment:
      - DB_URL=postgresql://back:root@db:5432/cardboard_bank
      - AUTH_PORT=80
