version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: toor
    volumes:
      - .build/.data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
