global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  static_configs:
  - targets: ['localhost:9090']
    labels:
      group: 'prometheus'
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
